name: Practising the ci pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build-test:

    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout the code
        uses: "actions/checkout@v4"
      
      - name: setup node
        uses: "actions/setup-node@v4"
        with:
          node-version: 20

      - name: Installing dependencies
        run: npm install

      - name: Running the tests here
        run: npm test

      - name: Run app
        run: node app.js  